run_name: "qwenInstruct_short"
model_id: "./base_models/Qwen2.5-1.5B-Instruct"
data_dirs: ["data/processed/nl2bash"]

recipe:
  model: "bnb/4bit"
  lora: "qwen/all_linear"
  lora_args:
    r: 16
    lora_dropout: 0.05
  sft: "bf16/stable"
  sft_args:
    lr: 2e-4
    n_epochs: 5
    max_length: 256
    packing: true
    per_device_train_batch_size: 16
    gradient_accumulation_steps: 1

eval_conf:
  model: ["bf16", "bnb/4bit"]
  lora_dir:
    - "./output/qwenInstruct0429_1852"
    - "./output/qwenInstruct_short0501_0107"
    - "./output/qwenInstruct_short0501_2322"

  max_new_tokens: 128
  batch_size: 256
