run_name: "qwenInstruct_smaller_r"
model_id: "./base_models/Qwen2.5-1.5B-Instruct"
data_dirs: ["data/processed/nl2bash"]

recipe:
  model: "bnb/4bit"
  lora: "qwen/all_linear"
  lora_args:
    r: 8
    lora_dropout: 0.05
  sft: "bf16/flexible"
  sft_args:
    learning_rate: 5e-5
    num_train_epochs: 3
    per_device_train_batch_size: 16
    gradient_accumulation_steps: 1
    packing: true
    max_length: 256
    eval_strategy: "steps"
    eval_steps: 50
    save_strategy: "steps"
    save_steps: 50
    load_best_model_at_end: true
    metric_for_best_model: "eval_loss"
    warmup_ratio: 0.1
    weight_decay: 0.01

eval_conf:
  model: ["bf16", "bnb/4bit"]
  lora_dir:
    - "./output/qwenInstruct0429_1852"
    - "./output/qwenInstruct_short0501_0107"
    - "./output/qwenInstruct_short0501_2322"
    - "./output/qwen0429_1607"
    - "./output/qwenInstruct_larger_r0502_0011"
  max_new_tokens: 128
  batch_size: 256
